### ISSUE TITLE
建议加一个更新日期的字段

### ISSUE THREAD

**Issue by Ratten-fanger** [pcrbot/HoshinoBot-plugins-index#175]
这样就不用一个一个点进去看有没有更新了

**Comment by azmiao** [comment]
主要是这个每次更新得靠作者自己过来更新，我觉得大多数应该很容易忘或者嫌麻烦吧

**Comment by azmiao** [comment]
而且如果用Github的Action自动爬取各个插件的commit时间的话，因为插件量多高频可能会被搞

**Comment by yuudi** [comment]
确实是个需求，我想想办法

**Comment by azmiao** [comment]
> 确实是个需求，我想想办法

雨滴佬太强了，请受本菜鸡一拜

**Comment by yuudi** [comment]
> 确实是个需求，我想想办法

想到了，你可以找个 RSS 阅读器，把要用的仓库的提交都订阅上，这样就可以知道作者更新了。

feed 地址：`https://github.com/<user>/<repo>/commits/<branch>.atom`

比如：<https://github.com/pcrbot/HoshinoBot-plugins-index/commits/master.atom>

**Comment by azmiao** [comment]
> 

啊这，那不是只能订阅自己关注的插件吗2333，我之前也写了个监控仓库commit的插件，不过我感觉他这是想要在索引按更新时间查找这样的

**Comment by yuudi** [comment]
> 
> 啊这，那不是只能订阅自己关注的插件吗2333，我之前也写了个监控仓库commit的插件，不过我感觉他这是想要在索引按更新时间查找这样的

正常的 RSS 阅读器都可以按时间查看的吧

**Comment by azmiao** [comment]
> > 啊这，那不是只能订阅自己关注的插件吗2333，我之前也写了个监控仓库commit的插件，不过我感觉他这是想要在索引按更新时间查找这样的
> 
> 正常的 RSS 阅读器都可以按时间查看的吧

额，不是。。。他这意思不是说想让索引里的每个插件都显示更新时间方便看插件是否有更新吗

**Comment by Ratten-fanger** [comment]
> 

对，

**Comment by Ratten-fanger** [comment]
> 

对，最好是能索引里多一个更新时间的维度。可惜我是菜鸡，我也没想到啥实现办法

**Comment by azmiao** [comment]
> > 
> 
> 对，最好是能索引里多一个更新时间的维度。可惜我是菜鸡，我也没想到啥实现办法

那就用Action呗不过频次高会炸，设置时间间隔每天半夜更新一次，虽然量有点大

**Comment by SonderXiaoming** [comment]
是个好功能，我插件经常大更新。

**Comment by yuudi** [comment]
那我试试做个 action

**Comment by azmiao** [comment]
> 那我试试做个 action

啊这，你已经在写了吗，那我就不写了，正好要出去玩儿了，另外获取更新日期可以直接用我那个github_reminder，给你省点力hhh，虽然自己写也不了几分钟（

**Comment by yuudi** [comment]
> 那我试试做个 action

![图片](https://user-images.githubusercontent.com/26199752/193946262-c33931e3-bcda-4347-adee-b8cf65c112d3.png)

**Comment by azmiao** [comment]
有大佬写就是好，看样子没啥问题了（
