### ISSUE TITLE
更新时间

### ISSUE THREAD

**Issue by RSRH-Rs** [pcrbot/HoshinoBot-plugins-index#210]
更新时间是自动的嘛，还是说要再次提交？

**Comment by azmiao** [comment]
自动会刷新的

**Comment by RSRH-Rs** [comment]
> 自动会刷新的

为什么我提交的两个都不刷新，格式错了嘛😢

**Comment by azmiao** [comment]
> > 自动会刷新的
> 
> 为什么我提交的两个都不刷新，格式错了嘛😢

别急，因为这个对实时性要求不高，更新频次设置的很低，然后每次只更新几个，等个几天或者十几天就有了，

**Comment by RSRH-Rs** [comment]
> > > 自动会刷新的
> > 
> > 为什么我提交的两个都不刷新，格式错了嘛😢
> 
> 别急，因为这个对实时性要求不高，更新频次设置的很低，然后每次只更新几个，等个几天或者十几天就有了，

好的好的谢谢~
